[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind=0.0.0.0:$PORT --workers=2 --timeout=120 --worker-class=gthread --threads=4 main:app"

healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.env]
PYTHONUNBUFFERED = "1"

[[services]]
name = "web"


