[build]
builder = "nixpacks"
buildCommand = """
pip install -r requirements.txt 
"""

[deploy]
startCommand = "ls && pg_restore -v -d $DATABASE_URL --no-owner --no-privileges /app/recipe_db_dump.custom && gunicorn --bind=0.0.0.0:$PORT main:app"

healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.env]
PYTHONUNBUFFERED = "1"

[[services]]
name = "web"


